rails_app/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  namespace :request do
      get 'get'
      get 'post'
      get 'put'
  end

end

rails_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails_app/app/controllers/request_controller.rb
require 'open-uri'
require "net/http"
require "uri"

class RequestController < ApplicationController
  def get
    example_com_html = open('http://localhost:9090/hello_world?param=value').read
    render html: example_com_html.html_safe
  end

  def post
    response = Net::HTTP.post_form(
      URI.parse("http://localhost:9090/post"),
      {"q" => "My query", "per_page" => "50"}
    )
    render json: response.body
  end

  def put
    uri = URI('http://localhost:9090/put')
    http = Net::HTTP.new(uri.host, uri.port)
    req = Net::HTTP::Put.new(
      uri.path,
      {'Content-Type' =>'application/json'}
    )
    req.body = { name: 'John Doe', role: 'agent' }.to_json
    res = http.request(req)
    render json: res.body
  end
end

rails_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

rails_app/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-no-turbolink>

<%= yield %>

</body>
</html>

rails_app/app/views/welcome/index.html.erb
<h1>Ruby Inspector demo rails app</h1>

<%= link_to('Make a get request', request_get_path) %>
<br>
<%= link_to('Make a post request', request_post_path) %>
<br>
<%= link_to('Make a put request', request_put_path) %>